version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    network_mode: service:mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
